version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions-dependencies:
        patterns:
          - "@actions/*"
      build-tools:
        patterns:
          - "@vercel/ncc"
    allow:
      - dependency-type: "direct"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
