name: 'JabRef Action'
description: 'Runs JabRef tasks'
author: 'JabRef e.V.'
inputs:
  bibfile:
    description: 'BibTeX file'
    required: true
  output-format:
    description: 'Output format: csv, errorformat, github-actions or txt'
    required: false
    default: 'errorformat'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bibfile }}
    - check
    - consistency
    - ${{ inputs.bibfile }}
    - --porcelain
    - --output-format=${{ inputs.output-format }}
