name: 'JabRef Action'
description: 'Runs JabRef tasks'
author: 'JabRef e.V.'
inputs:
  bibfile:
    description: 'BibTeX file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bibfile }}
    - check-consistency
    - --input=${{ inputs.bibfile }}
    - --porcelain
