name: Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run jabref-action
        uses: ./ # use local action
        with:
          bibfile: test/test.bib
