name: Check

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: JabRef/jabref-demonstration-libraries
          path: jabref-demonstration-libraries
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check test/consistent.bib
        uses: ./
        with:
          bibfile: test/consistent.bib
      - name: Check test/inconsistent.bib
        continue-on-error: true
        uses: ./
        id: inconsistent
        with:
          bibfile: test/inconsistent.bib
      - name: inconsistent did not fail?
        if: steps.inconsistent.outcome == 'success'
        run: exit 1
      - name: Check jabref-demonstration-libraries/chocolate/Chocolate.bib
        continue-on-error: true
        uses: ./
        id: chocolate
        with:
          bibfile: jabref-demonstration-libraries/chocolate/Chocolate.bib
      - name: chocolate did not fail?
        if: steps.chocolate.outcome == 'success'
        run: exit 1
